[package]
name = "farms"
description = "Kamino Farms"
version = "1.6.1"
edition = "2021"
license = "BUSL-1.1"
publish = false

[lib]
crate-type = ["cdylib", "lib"]
name = "farms"
doctest = false

[features]
no-entrypoint = []
test-bpf = []
no-idl = []
cpi = ["no-entrypoint"]
devnet = []
localnet = []
mainnet = []
derive-serde = ["serde"]

[dependencies]
anchor-lang = "0.28.0"
anchor-spl = "0.28.0"
spl-token = "3.5.0"
decimal-wad = "0.1.9"
num-traits = "0.2"
num-derive = "0.3"
num_enum = "0.5.0"
solana-security-txt = "1.1.1"
serde = { version = "1.0.134", optional = true }
static_assertions = "1.1.0"
bytemuck = { version = "1.4.0", features = ["min_const_generics", "derive"] }
uint = "0.9.5"

[dev-dependencies]
solana-program-test = "1.16.0"
solana-sdk = "1.16.0"
tokio = { version = "1.25", features = ["full"] }
proptest = "1.0"
num-bigint = "0.4"
num-rational = "0.4"
rand = "0.8"